Data Race: {
  shape: sequence_diagram

  g1: Goroutine
  v: Variable
  g2: Goroutine

  v."value is 0"

  g1 -> v: Get Value
  g2 -> v: Get Value

  g1 -> v: +=10
  g2 -> v: +=5

  v."What is the value now?"


}
